### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by doxakis** [Gcaya/Climbing-Hold-Recognition#1]
Hi,

feel free to address what you want :

- `change_hue` is not defined in the script (should be `change_hsv` ?)
- change absolute path to relative path (you can remove `D:\Climbing-Hold-Recognition\`)
- `cv_image = cv2.imread(r'D:\Climbing-Hold-Recognition\Sample-Data\\3.png')` reference the image 3.png, which is not commit yet in the git repo.

Thanks!

**Comment by Gcaya** [comment]
Hi,

Thank you for the input, I am working on it and will let you know once the changes have been made.

**Comment by Gcaya** [comment]
Ok so I've made the following modifications 

- Added some sample pictures to give more color diversity
- You can now execute the script and give it two args, source path and destination path
- There is no more undefined function

So far the script will only show you what has been detected with opencv, but I'm working on the function to target individual holds and extract them out of the original picture.
